{"uuid": "f9517b84-fa49-4c14-bda4-f24dffd38f9a", "children": ["95185d49-ca34-4196-ae65-5f740ac83919"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\r\n\n\n", "trace": "  File \"F:\\QA-Engineer\\Python_projects\\qa_guru\\qa_guru_python_10_jenkins\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"F:\\QA-Engineer\\Python_projects\\qa_guru\\qa_guru_python_10_jenkins\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"F:\\QA-Engineer\\Python_projects\\qa_guru\\qa_guru_python_10_jenkins\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"F:\\QA-Engineer\\Python_projects\\qa_guru\\qa_guru_python_10_jenkins\\tests\\conftest.py\", line 54, in setup_browser\n    driver = webdriver.Remote(\n  File \"F:\\QA-Engineer\\Python_projects\\qa_guru\\qa_guru_python_10_jenkins\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"F:\\QA-Engineer\\Python_projects\\qa_guru\\qa_guru_python_10_jenkins\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"F:\\QA-Engineer\\Python_projects\\qa_guru\\qa_guru_python_10_jenkins\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"F:\\QA-Engineer\\Python_projects\\qa_guru\\qa_guru_python_10_jenkins\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 211, in check_response\n    raise exception_class(value)\n"}, "start": 1659042219832, "stop": 1659042220263}], "start": 1659042219832, "stop": 1659042220678}